### ISSUE TITLE
alpha fitting in GeneralizedLocalExplainer

### ISSUE THREAD

**Issue by kudkudak** [marcotcr/lime-experiments#1]
Hello,

I have a question about fitting alpha when `lambda_` is not passed in `GeneralizedLocalExplainer`. Should `alpha` and `chosen_coefs` that are found using `lars_path` in https://github.com/marcotcr/lime-experiments/blob/master/explainers.py#L205 not used in https://github.com/marcotcr/lime-experiments/blob/master/explainers.py#L208 ?

**Comment by marcotcr** [comment]
Hello,
This is a point I've gone back and forth on.
I'm using Lasso for feature selection, in an effort to approximate the problem of finding the best w such that the number of nonzeros in w is less than K, which is why I'm computing the lars path. Now, the weights found with lambda such that |w|_0 = K are going to be biased (especially with the high lambdas required when K is small), which is why I'm learning new weights just with those features. I should probably have still added some regularization (I set lambda to 0 in the experiments in the paper).

Since doing these experiments, I've convinced myself that this lasso approximation is not ideal, and that I should use another feature selection method in order to approximate this first step. The reason is that regularization part of the objective ends up conflicting with the fit part, so that features with high weight end up not getting selected sometimes because they incur too much loss in the regularization part. This ends up producing non intuitive feature choices sometimes. Using this Lasso approximation still works, but I now think it is not the best.

On another note, please take a look at [the package we are working on](https://github.com/marcotcr/lime). This repository (lime-experiments) is frozen with the version I had when I did the paper experiments, for reproducibility. The version in [this repository](https://github.com/marcotcr/lime) has better quality code, visualization options and other minor improvements.

**Comment by kudkudak** [comment]
Thanks for the explanation and the link to the package, I haven't noticed it :) I will close the issue now
