### ISSUE TITLE
Code freeze

### ISSUE THREAD

**Issue by remram44** [marcotcr/lime-experiments#2]
Hi,

I'm very surprised to see you use GitHub in this way, to publish a single, apparently frozen version of research code. It is somewhat inadequate, offers no guarantee of preservation or frozen-ness, no unique URL (should you someday decide to change your GitHub handle, this URL will die).

Have you considered something like [Zenodo](https://zenodo.org/), which preserves artifacts on CERN's repository, is free, mints DOIs, and integrates with GitHub to import code automatically when you tag?

Another solution is the [OSF](https://osf.io/), which is also free, mints DOIs and integrates with GitHub, though it is meant for more than snapshotting.

I guess it is too late now that your paper refers to this repository -- I just thought I'd offer some unwanted advice. Nevertheless, thank you for your concern and efforts about reproducibility.

Cheers!

**Comment by marcotcr** [comment]
It's true that there is no 'guarantee of preservation of frozen-ness' in github, but one merely has to look at the timestamps of the last edits - and I'm not touching this repository anymore.
I froze it in this way so that one can reproduce my experiments exactly if such is desired. However, if one is interested in actually using LIME, one would have to look at [another repository](https://github.com/marcotcr/lime), which is maybe what I would consider my 'research code'.

It does seem that the solutions you suggested are more appropriate for what I tried to do here.
I had never heard of either of those, so thanks for the tip.
=]
