### ISSUE TITLE
Building SP LIME from experiment 5.4

### ISSUE THREAD

**Issue by sofiaherrero** [marcotcr/lime-experiments#8]
Hello,

I'm trying to implement SP LIME using the code you have in compare_classifiers.py. I was planning on re-using the functions `submodular_fn, submodular_pick` and `greedy`. Then just call` pick = pick_function(pickled_map, 'lime', B)` as you have it (but with the explanations instead of pickled_map). But I have noticed that you have re-implemented LIME in explainers.py and you use the `GeneralizedLocalExplainer` which does things different to LIME (shifts the labels with the mean, uses Lasso instead of Ridge, etc). I was planning on using LIME from the lime repo to pass the explanations (I guess not the object but the list of tuples (feature_id, weights)) to `pick = pick_function(pickled_map, 'lime', B)`.

My question is, is there anything in the GeneralizedLocalExplainer that is important for SP LIME and I should take into account to build SP LIME? I cannot figure out exactly why using the mean or other thins is done since there aren't many comments. Thanks!

**Comment by marcotcr** [comment]
Sorry for the long delay in responding. The LIME package is actually the reimplementation of explainers.py, not the other way around :). Explainer.py is how we did it in the paper (which is why we use Lasso, etc). We are shifting the mean because we didn't use an intercept.

The answer to your question is: no, there is nothing in GeneralizedLocalExplainer that is important for SP LIME.
